#include "flex_runtime.h"      // barriers, IDs, EOC, local()/hbm_addr(), flex_is_dm_core()
#include "flex_printf.h"       // lightweight printf
#include "flex_cluster_arch.h" // ARCH_NUM_* (generated by `make hw`)
#include "flex_alloc.h"        // alloc APIs for L1 arenas
#include "flex_dma_pattern.h"  // flex_dma_async_1d, flex_dma_async_wait_all
#include "flex_dump.h"         // optional HBM dump helpers
#include "soc_daml.h"          // your metadata/intersection runtime
#include <stdint.h>

/* ------------ L1 test arenas for each (cluster,core) ------------ */
#define L1_MEM_SIZE 4096u
static uint8_t l1_mem[(ARCH_NUM_CLUSTER_X*ARCH_NUM_CLUSTER_Y)]
                     [ARCH_NUM_CORE_PER_CLUSTER]
                     [L1_MEM_SIZE];

static inline uint32_t as_u32(const void *p) { return (uint32_t)(uintptr_t)p; }

static void build_maps(void *base[(ARCH_NUM_CLUSTER_X*ARCH_NUM_CLUSTER_Y)]
                              [ARCH_NUM_CORE_PER_CLUSTER],
                       uint32_t size[(ARCH_NUM_CLUSTER_X*ARCH_NUM_CLUSTER_Y)]
                                    [ARCH_NUM_CORE_PER_CLUSTER],
                       uint32_t clusters, uint32_t cores)
{
  for (uint32_t c = 0; c < clusters; ++c)
    for (uint32_t k = 0; k < cores; ++k) {
      base[c][k] = (void*)&l1_mem[c][k][0];
      size[c][k] = L1_MEM_SIZE;
    }
}

static void print_core_snapshot(int c, int k)
{
  uint32_t n = soc_daml_get_core_free_count(c, k);
  printf("[C%u-K%u] snapshot_count=%u\n", (unsigned)c, (unsigned)k, (unsigned)n);
  uint32_t lim = (n > 8u) ? 8u : n;
  for (uint32_t i = 0; i < lim; ++i) {
    const daml_block_t *b = &soc_daml_get_core_free_list(c, k)[i];
    printf("  #%u addr=0x%08x size=%u\n",
           (unsigned)i, as_u32(b->addr), (unsigned)b->size);
  }
  if (n > lim) printf("  ... (%u more)\n", (unsigned)(n - lim));
}

static void print_cluster_common(int c)
{
  uint32_t n = soc_daml_get_cluster_common_count(c);
  printf("[C%u] cluster_common=%u\n", (unsigned)c, (unsigned)n);
  uint32_t lim = (n > 8u) ? 8u : n;
  for (uint32_t i = 0; i < lim; ++i) {
    const daml_block_t *b = &soc_daml_get_cluster_common(c)[i];
    printf("  #%u addr=0x%08x size=%u\n",
           (unsigned)i, as_u32(b->addr), (unsigned)b->size);
  }
  if (n > lim) printf("  ... (%u more)\n", (unsigned)(n - lim));
}

int main(void)
{
  uint32_t eoc_val = 0;

  flex_barrier_xy_init();
  flex_global_barrier_xy();

  const uint32_t mesh_x   = ARCH_NUM_CLUSTER_X;
  const uint32_t mesh_y   = ARCH_NUM_CLUSTER_Y;
  const uint32_t clusters = mesh_x * mesh_y;
  const uint32_t cores    = ARCH_NUM_CORE_PER_CLUSTER;

  if (flex_get_cluster_id() == 0 && flex_get_core_id() == 0) {
    printf("[BOOT] Using %ux%u clusters, %u cores/cluster\n", mesh_x, mesh_y, cores);
  }

  soc_daml_set_runtime_dims(clusters, cores);

  static void *base_addrs[(ARCH_NUM_CLUSTER_X*ARCH_NUM_CLUSTER_Y)][ARCH_NUM_CORE_PER_CLUSTER];
  static uint32_t sizes[(ARCH_NUM_CLUSTER_X*ARCH_NUM_CLUSTER_Y)][ARCH_NUM_CORE_PER_CLUSTER];

  if (flex_get_cluster_id() == 0 && flex_get_core_id() == 0) {
    printf("[BOOT] Building allocator maps...\n");
    build_maps(base_addrs, sizes, clusters, cores);
    printf("[BOOT] Initializing allocators in HBM...\n");
    soc_daml_init_allocators(base_addrs, sizes);
  }
  flex_global_barrier_xy();

  const int my_cid  = (int)flex_get_cluster_id();
  const int my_core = (int)flex_get_core_id();
  if (((unsigned)my_cid < clusters) && ((unsigned)my_core < cores)) {
    soc_daml_upload_free_list(my_cid, my_core);
  }
  flex_global_barrier_xy();

  if (flex_get_cluster_id() == 0 && flex_get_core_id() == 0) {
    printf("\n=== Phase 1: Per-core snapshots ===\n");
    for (uint32_t c = 0; c < clusters; ++c)
      for (uint32_t k = 0; k < cores; ++k)
        print_core_snapshot((int)c,(int)k);
  }
  flex_global_barrier_xy();

  if (flex_get_cluster_id() == 0 && flex_get_core_id() == 0) {
    printf("\n=== Phase 2: Cluster-wide intersections ===\n");
    for (uint32_t c = 0; c < clusters; ++c) {
      soc_daml_build_cluster_common((int)c);
      print_cluster_common((int)c);
    }
  }
  flex_global_barrier_xy();

  if (my_cid == 0 && my_core == 0) {
    printf("\n[C0-K0] alloc 128, then 96; free first; re-snapshot\n");
    void *p0 = flex_l1_block_alloc(0,0,128u);
    void *p1 = flex_l1_block_alloc(0,0,96u);
    printf("[C0-K0] p0=0x%08x p1=0x%08x\n", as_u32(p0), as_u32(p1));
    if (p0) flex_l1_block_free(0,0,p0);
  }
  flex_global_barrier_xy();

  if (flex_get_cluster_id() == 0 && flex_get_core_id() == 0) {
    printf("\n=== Phase 3: Intersections after mutations ===\n");
    for (uint32_t c = 0; c < clusters; ++c) {
      soc_daml_build_cluster_common((int)c);
      print_cluster_common((int)c);
    }
  }
  flex_global_barrier_xy();

  /* ------------------- HBM via iDMA tutorial flow ------------------- */
  if (flex_is_dm_core() && (flex_get_cluster_id() == 0)) {
    printf("\n=== HBM <-> L1 via iDMA (tutorial pattern) ===\n");

    // Suppose A is preloaded at HBM offset 0 (see make_preload_elf)
    uint64_t A_hbm_offset   = 0;                 // HBM base + 0
    uint32_t A_l1_offset    = 0;                 // start of local L1 buffer
    uint32_t A_size_bytes   = 64 * 64 * 2;       // 64x64 fp16

    volatile uint16_t* l1p = (volatile uint16_t*)local(A_l1_offset);

    printf("[Before HBM->L1] first 8 L1 words:\n");
    for (int i = 0; i < 8; ++i) printf("  0x%04x\n", l1p[i]);

    // HBM -> L1
    flex_dma_async_1d(local(A_l1_offset),
                      hbm_addr(A_hbm_offset),
                      A_size_bytes);
    printf("[Load HBM->L1] async iDMA...\n");
    flex_dma_async_wait_all();

    printf("[After  HBM->L1] first 8 L1 words:\n");
    for (int i = 0; i < 8; ++i) printf("  0x%04x\n", l1p[i]);

    // Store back L1 -> HBM to a new region (e.g., 4 * A_size_bytes)
    uint64_t A_copy_hbm_offset = 4ull * (uint64_t)A_size_bytes;
    flex_dma_async_1d(hbm_addr(A_copy_hbm_offset),
                      local(A_l1_offset),
                      A_size_bytes);
    printf("[Store L1->HBM] async iDMA...\n");
    flex_dma_async_wait_all();

    // Optional: dump both regions to a file
    printf("[Dump HBM regions]\n");
    flex_dump_open();
    flex_dump_hbm(A_hbm_offset,       A_size_bytes);
    flex_dump_hbm(A_copy_hbm_offset,  A_size_bytes);
    flex_dump_close();
  }
  flex_global_barrier_xy();
  /* ------------------------------------------------------------------ */

  flex_eoc(eoc_val);
  return 0;
}
