#include "flex_runtime.h"      // barriers, IDs, EOC, helpers
#include "flex_printf.h"       // tiny printf (no <stdio.h>)
#include "flex_cluster_arch.h" // ARCH_NUM_* macros (generated after `make hw`)
#include "flex_alloc.h"        // MIN_BLOCK_SIZE, alloc APIs
#include "soc_daml.h"          // P1 APIs (snapshots/intersections)
#include <stdint.h>

static inline uint32_t as_u32(const void *p) { return (uint32_t)(uintptr_t)p; }

/* Build the per-(cluster,core) L1 allocator map using the REAL L1 heap window.
   The L1 logical address map is identical for all clusters; we pass the same
   (base,size) per core for each cluster. */
static void build_l1_allocator_maps(void *base[(ARCH_NUM_CLUSTER_X*ARCH_NUM_CLUSTER_Y)]
                                            [ARCH_NUM_CORE_PER_CLUSTER],
                                    uint32_t size[(ARCH_NUM_CLUSTER_X*ARCH_NUM_CLUSTER_Y)]
                                                 [ARCH_NUM_CORE_PER_CLUSTER],
                                    uint32_t clusters, uint32_t cores)
{
#if !defined(ARCH_CLUSTER_HEAP_BASE) || !defined(ARCH_CLUSTER_HEAP_END)
# error "ARCH_CLUSTER_HEAP_BASE/END must be defined in flex_cluster_arch.h (generated by make hw)."
#endif
  const uint32_t heap_base = (uint32_t)ARCH_CLUSTER_HEAP_BASE;
  const uint32_t heap_end  = (uint32_t)ARCH_CLUSTER_HEAP_END;
  const uint32_t heap_size = (heap_end > heap_base) ? (heap_end - heap_base) : 0u;
  const uint32_t align     = (uint32_t)MIN_BLOCK_SIZE;

  /* Defensive checks + prints */
  if (flex_get_cluster_id() == 0 && flex_get_core_id() == 0) {
    printf("[BOOT] L1 heap range: [0x%08x, 0x%08x) size=0x%08x\n",
           heap_base, heap_end, heap_size);
    printf("[BOOT] MIN_BLOCK_SIZE (align) = %u bytes\n", (unsigned)align);
  }

  /* Split equally across cores; align bases up and sizes down. */
  uint32_t slice = (cores > 0u) ? (heap_size / cores) : 0u;
  if (slice >= align) slice = (slice / align) * align;  /* align down */

  for (uint32_t c = 0; c < clusters; ++c) {
    for (uint32_t k = 0; k < cores; ++k) {

      uint32_t raw_base = heap_base + k * slice;
      /* align base up */
      uint32_t base_k = (raw_base + (align - 1u)) & ~(align - 1u);
      /* size is slice minus the alignment shift we just introduced */
      uint32_t shift  = base_k - raw_base;
      uint32_t size_k = (slice > shift) ? (slice - shift) : 0u;
      /* align size down */
      if (size_k >= align) size_k = (size_k / align) * align;

      /* Clamp to heap_end, avoid overflow */
      if ((base_k + size_k) > heap_end) {
        if (heap_end > base_k) size_k = heap_end - base_k;
        else size_k = 0u;
        if (size_k >= align) size_k = (size_k / align) * align;
      }

      base[c][k] = (void*)base_k;
      size[c][k] = size_k;

      if (flex_get_cluster_id() == 0 && flex_get_core_id() == 0) {
        printf("[MAP] c=%u k=%u  base=0x%08x  size=0x%08x  end=0x%08x\n",
               (unsigned)c, (unsigned)k, base_k, size_k, base_k + size_k);
      }
    }
  }
}

/* Debug print helpers */
static void print_core_snapshot(int c, int k)
{
  uint32_t n = soc_daml_get_core_free_count(c, k);
  printf("[C%u-K%u] snapshot_count=%u\n", (unsigned)c, (unsigned)k, (unsigned)n);
  uint32_t lim = (n > 8u) ? 8u : n;
  for (uint32_t i = 0; i < lim; ++i) {
    const daml_block_t *b = &soc_daml_get_core_free_list(c, k)[i];
    printf("  #%u addr=0x%08x size=%u\n",
           (unsigned)i, as_u32(b->addr), (unsigned)b->size);
  }
  if (n > lim) printf("  ... (%u more)\n", (unsigned)(n - lim));
}

static void print_cluster_common(int c)
{
  uint32_t n = soc_daml_get_cluster_common_count(c);
  printf("[C%u] cluster_common=%u\n", (unsigned)c, (unsigned)n);
  uint32_t lim = (n > 8u) ? 8u : n;
  for (uint32_t i = 0; i < lim; ++i) {
    const daml_block_t *b = &soc_daml_get_cluster_common(c)[i];
    printf("  #%u addr=0x%08x size=%u\n",
           (unsigned)i, as_u32(b->addr), (unsigned)b->size);
  }
  if (n > lim) printf("  ... (%u more)\n", (unsigned)(n - lim));
}

int main(void)
{
  uint32_t eoc_val = 0;

  flex_barrier_xy_init();
  flex_global_barrier_xy();

  const uint32_t mesh_x   = ARCH_NUM_CLUSTER_X;
  const uint32_t mesh_y   = ARCH_NUM_CLUSTER_Y;
  const uint32_t clusters = mesh_x * mesh_y;
  const uint32_t cores    = ARCH_NUM_CORE_PER_CLUSTER;

  if (flex_get_cluster_id() == 0 && flex_get_core_id() == 0) {
    printf("[SystemInfo]: num_cluster_x = %u, num_cluster_y = %u\n", mesh_x, mesh_y);
    printf("[BOOT] Using %ux%u clusters, %u cores/cluster\n", mesh_x, mesh_y, cores);
  }

  /* Tell soc_daml the runtime dims to respect at run time */
  soc_daml_set_runtime_dims(clusters, cores);

  /* Per-(cluster,core) allocator map */
  static void *base_addrs[(ARCH_NUM_CLUSTER_X*ARCH_NUM_CLUSTER_Y)][ARCH_NUM_CORE_PER_CLUSTER];
  static uint32_t sizes[(ARCH_NUM_CLUSTER_X*ARCH_NUM_CLUSTER_Y)][ARCH_NUM_CORE_PER_CLUSTER];

  /* Only C0-K0 builds and initializes the allocators, then we barrier */
  if (flex_get_cluster_id() == 0 && flex_get_core_id() == 0) {
    printf("[BOOT] Building allocator maps...\n");
    build_l1_allocator_maps(base_addrs, sizes, clusters, cores);
    printf("[BOOT] Initializing allocators in HBM...\n");
    soc_daml_init_allocators(base_addrs, sizes);
    printf("[BOOT] Allocators initialized.\n");
  }
  flex_global_barrier_xy();

  /* Each core uploads its own free-list snapshot */
  const int my_cid  = (int)flex_get_cluster_id();
  const int my_core = (int)flex_get_core_id();
  if (((unsigned)my_cid < clusters) && ((unsigned)my_core < cores)) {
    soc_daml_upload_free_list(my_cid, my_core);
  }
  flex_global_barrier_xy();

  /* Phase 1: show per-core snapshots (from C0-K0) */
  if (flex_get_cluster_id() == 0 && flex_get_core_id() == 0) {
    printf("\n=== Phase 1: Per-core snapshots ===\n");
    for (uint32_t c = 0; c < clusters; ++c)
      for (uint32_t k = 0; k < cores; ++k)
        print_core_snapshot((int)c,(int)k);
  }
  flex_global_barrier_xy();

  /* Phase 2: cluster-wide intersections */
  if (flex_get_cluster_id() == 0 && flex_get_core_id() == 0) {
    printf("\n=== Phase 2: Cluster-wide intersections ===\n");
    for (uint32_t c = 0; c < clusters; ++c) {
      soc_daml_build_cluster_common((int)c);
      print_cluster_common((int)c);
    }
  }
  flex_global_barrier_xy();

  /* Mutate one allocator in C0-K0 and re-check */
  if (my_cid == 0 && my_core == 0) {
    printf("\n[C0-K0] alloc 128, then 96; free first; re-snapshot\n");
    void *p0 = flex_l1_block_alloc(0,0,128u);
    void *p1 = flex_l1_block_alloc(0,0,96u);
    printf("[C0-K0] p0=0x%08x p1=0x%08x\n", as_u32(p0), as_u32(p1));
    if (p0) flex_l1_block_free(0,0,p0);
    /* Upload fresh snapshot for this core after changes */
    soc_daml_upload_free_list(0,0);
  }
  flex_global_barrier_xy();

  if (flex_get_cluster_id() == 0 && flex_get_core_id() == 0) {
    printf("\n=== Phase 3: Intersections after mutations ===\n");
    for (uint32_t c = 0; c < clusters; ++c) {
      soc_daml_build_cluster_common((int)c);
      print_cluster_common((int)c);
    }
  }
  flex_global_barrier_xy();

  /* Quick HBM sanity check */
  if (flex_get_cluster_id() == 0 && flex_get_core_id() == 0) {
    printf("\n=== HBM: alloc->write->read->free ===\n");
    void *h = flex_hbm_malloc(64u);
    printf("[HBM] alloc 64 -> 0x%08x\n", as_u32(h));
    if (h) {
      volatile uint8_t *q = (volatile uint8_t*)h;
      for (uint32_t i = 0; i < 64u; ++i) q[i] = (uint8_t)i;
      uint32_t ok = 1u;
      for (uint32_t i = 0; i < 64u; ++i) if (q[i] != (uint8_t)i) { ok = 0u; break; }
      printf("[HBM] verify=%s\n", ok ? "OK" : "FAIL");
      flex_hbm_free((void*)h);
    }
  }

  flex_global_barrier_xy();
  flex_eoc(eoc_val);
  return 0;
}
