#pragma once
/*
 * soc_daml.h — SoftHier P1 runtime (HBM-visible allocation metadata)
 *
 * Uses platform dimensions from flex_cluster_arch.h (generated by `make hw`).
 * - Per-core upload of L1 free-list snapshots into HBM
 * - Cluster-wide + system-wide intersections (free in ALL cores/clusters)
 * - Spinlocks + fences for correctness
 * - No memset/memcpy/stdio (GVSOC-safe)
 */

#include <stdint.h>
#include <stddef.h>
#include "flex_cluster_arch.h"  // ARCH_NUM_* macros
#include "flex_alloc.h"         // alloc_t, alloc_block_t APIs

#ifndef ARCH_NUM_CLUSTER_X
#error "ARCH_NUM_CLUSTER_X not defined. Generate flex_cluster_arch.h via `make hw` and check include paths."
#endif
#ifndef ARCH_NUM_CLUSTER_Y
#error "ARCH_NUM_CLUSTER_Y not defined. Generate flex_cluster_arch.h via `make hw` and check include paths."
#endif
#ifndef ARCH_NUM_CORE_PER_CLUSTER
#error "ARCH_NUM_CORE_PER_CLUSTER not defined. Generate flex_cluster_arch.h via `make hw` and check include paths."
#endif

#define NUM_CLUSTER_X        (ARCH_NUM_CLUSTER_X)
#define NUM_CLUSTER_Y        (ARCH_NUM_CLUSTER_Y)
#define NUM_CLUSTERS         ((NUM_CLUSTER_X) * (NUM_CLUSTER_Y))
#define CORES_PER_CLUSTER    (ARCH_NUM_CORE_PER_CLUSTER)

/* Keep metadata small to fit i-mem budget when logs are enabled */
#ifndef MAX_FREE_BLOCKS_PER_CORE
#define MAX_FREE_BLOCKS_PER_CORE  64u
#endif
#ifndef MAX_COMMON_BLOCKS
#define MAX_COMMON_BLOCKS         64u
#endif

typedef struct {
  void    *addr;   /* start address of the free block (block header) */
  uint32_t size;   /* size in bytes of the free block */
} daml_block_t;

/* ---------- HBM-resident global state ---------- */
__attribute__((section(".hbm"))) alloc_t g_hbm_l1_allocators[NUM_CLUSTERS][CORES_PER_CLUSTER];
__attribute__((section(".hbm"))) daml_block_t g_hbm_core_free[NUM_CLUSTERS][CORES_PER_CLUSTER][MAX_FREE_BLOCKS_PER_CORE];
__attribute__((section(".hbm"))) volatile uint32_t g_hbm_core_free_count[NUM_CLUSTERS][CORES_PER_CLUSTER];
__attribute__((section(".hbm"))) daml_block_t g_hbm_cluster_common[NUM_CLUSTERS][MAX_COMMON_BLOCKS];
__attribute__((section(".hbm"))) volatile uint32_t g_hbm_cluster_common_count[NUM_CLUSTERS];
__attribute__((section(".hbm"))) daml_block_t g_hbm_system_common[MAX_COMMON_BLOCKS];
__attribute__((section(".hbm"))) volatile uint32_t g_hbm_system_common_count;
__attribute__((section(".hbm"))) volatile int g_cluster_lock[NUM_CLUSTERS];
__attribute__((section(".hbm"))) volatile int g_global_lock;

/* ---------- Runtime dimensions (bounds) ---------- */
__attribute__((section(".hbm"))) static volatile uint32_t g_rt_num_clusters = NUM_CLUSTERS;
__attribute__((section(".hbm"))) static volatile uint32_t g_rt_cores_per_cluster = CORES_PER_CLUSTER;

static inline void soc_daml_set_runtime_dims(uint32_t num_clusters, uint32_t cores_per_cluster) {
  g_rt_num_clusters      = (num_clusters      <= NUM_CLUSTERS)      ? num_clusters      : NUM_CLUSTERS;
  g_rt_cores_per_cluster = (cores_per_cluster <= CORES_PER_CLUSTER) ? cores_per_cluster : CORES_PER_CLUSTER;
}

/* ---------- tiny utils (no libc) ---------- */
static inline void daml_zero_bytes(volatile void *ptr, uint32_t n) {
  volatile uint8_t *q = (volatile uint8_t*)ptr; for (uint32_t i = 0; i < n; ++i) q[i] = 0u;
}
static inline void daml_fence(void) { __sync_synchronize(); }

static inline int daml_block_eq(const daml_block_t *a, const daml_block_t *b) {
  return (a->addr == b->addr) && (a->size == b->size);
}
static inline int daml_contains(const daml_block_t *list, uint32_t n, const daml_block_t *x) {
  for (uint32_t i = 0; i < n; ++i) if (daml_block_eq(&list[i], x)) return 1;
  return 0;
}

/* ---------- spinlocks ---------- */
static inline void daml_lock_cluster(int cid)   { while (__sync_lock_test_and_set(&g_cluster_lock[cid], 1)) { } }
static inline void daml_unlock_cluster(int cid) { __sync_lock_release(&g_cluster_lock[cid]); }
static inline void daml_lock_global(void)       { while (__sync_lock_test_and_set(&g_global_lock, 1)) { } }
static inline void daml_unlock_global(void)     { __sync_lock_release(&g_global_lock); }

/* ---------- bounds ---------- */
static inline int daml_in_bounds_cluster(int cid) {
  return ((unsigned)cid < NUM_CLUSTERS) && ((unsigned)cid < g_rt_num_clusters);
}
static inline int daml_in_bounds_cc(int cid, int core) {
  return ((unsigned)cid  < NUM_CLUSTERS) &&
         ((unsigned)core < CORES_PER_CLUSTER) &&
         ((unsigned)cid  < g_rt_num_clusters) &&
         ((unsigned)core < g_rt_cores_per_cluster);
}

/* ---------- init ---------- */
static inline void soc_daml_init_allocators(void *base[NUM_CLUSTERS][CORES_PER_CLUSTER],
                                            uint32_t size[NUM_CLUSTERS][CORES_PER_CLUSTER]) {
  for (uint32_t c = 0; c < NUM_CLUSTERS; ++c)
    for (uint32_t k = 0; k < CORES_PER_CLUSTER; ++k)
      flex_cluster_alloc_init(&g_hbm_l1_allocators[c][k], base[c][k], size[c][k]);

  for (uint32_t c = 0; c < NUM_CLUSTERS; ++c) {
    g_cluster_lock[c] = 0;
    g_hbm_cluster_common_count[c] = 0u;
    daml_zero_bytes(&g_hbm_cluster_common[c][0], (uint32_t)sizeof(g_hbm_cluster_common[c]));
    for (uint32_t k = 0; k < CORES_PER_CLUSTER; ++k) {
      g_hbm_core_free_count[c][k] = 0u;
      daml_zero_bytes(&g_hbm_core_free[c][k][0], (uint32_t)sizeof(g_hbm_core_free[c][k]));
    }
  }
  g_global_lock = 0;
  g_hbm_system_common_count = 0u;
  daml_zero_bytes(&g_hbm_system_common[0], (uint32_t)sizeof(g_hbm_system_common));
  daml_fence();
}

/* ---------- per-core snapshot upload ---------- */
static inline void soc_daml_upload_free_list(int cluster_id, int core_id) {
  if (!daml_in_bounds_cc(cluster_id, core_id)) return;
  alloc_t       *alloc = &g_hbm_l1_allocators[cluster_id][core_id];
  alloc_block_t *curr  = alloc->first_block;
  uint32_t count = 0u;

  daml_lock_cluster(cluster_id);
  g_hbm_core_free_count[cluster_id][core_id] = 0u;
  daml_fence();

  while (curr && (count < MAX_FREE_BLOCKS_PER_CORE)) {
    g_hbm_core_free[cluster_id][core_id][count].addr = (void*)curr;
    g_hbm_core_free[cluster_id][core_id][count].size = curr->size;
    curr  = curr->next;
    count += 1u;
  }

  daml_fence();
  g_hbm_core_free_count[cluster_id][core_id] = count;
  daml_unlock_cluster(cluster_id);
}

/* ---------- cluster-wide intersection ---------- */
static inline void soc_daml_build_cluster_common(int cluster_id) {
  if (!daml_in_bounds_cluster(cluster_id)) return;
  uint32_t out_cnt = 0u;

  daml_lock_cluster(cluster_id);
  g_hbm_cluster_common_count[cluster_id] = 0u;
  daml_fence();

  const daml_block_t *ref   = &g_hbm_core_free[cluster_id][0][0];
  const uint32_t      ref_n = g_hbm_core_free_count[cluster_id][0];

  for (uint32_t i = 0; i < ref_n && out_cnt < MAX_COMMON_BLOCKS; ++i) {
    const daml_block_t *X = &ref[i];
    int in_all = 1;
    for (uint32_t k = 1; k < g_rt_cores_per_cluster; ++k) {
      const daml_block_t *lst = &g_hbm_core_free[cluster_id][k][0];
      uint32_t lst_n = g_hbm_core_free_count[cluster_id][k];
      if (!daml_contains(lst, lst_n, X)) { in_all = 0; break; }
    }
    if (in_all) g_hbm_cluster_common[cluster_id][out_cnt++] = *X;
  }

  daml_fence();
  g_hbm_cluster_common_count[cluster_id] = out_cnt;
  daml_unlock_cluster(cluster_id);
}

/* ---------- system-wide intersection ---------- */
static inline void soc_daml_build_system_common(void) {
  uint32_t out_cnt = 0u;

  daml_lock_global();
  g_hbm_system_common_count = 0u;
  daml_fence();

  if (g_rt_num_clusters == 0u) { daml_unlock_global(); return; }

  const daml_block_t *ref   = &g_hbm_cluster_common[0][0];
  const uint32_t      ref_n = g_hbm_cluster_common_count[0];

  for (uint32_t i = 0; i < ref_n && out_cnt < MAX_COMMON_BLOCKS; ++i) {
    const daml_block_t *X = &ref[i];
    int in_all = 1;
    for (uint32_t c = 1; c < g_rt_num_clusters; ++c) {
      const daml_block_t *lst = &g_hbm_cluster_common[c][0];
      uint32_t lst_n = g_hbm_cluster_common_count[c];
      if (!daml_contains(lst, lst_n, X)) { in_all = 0; break; }
    }
    if (in_all) g_hbm_system_common[out_cnt++] = *X;
  }

  daml_fence();
  g_hbm_system_common_count = out_cnt;
  daml_unlock_global();
}

/* ---------- optional wrappers ---------- */
static inline void *flex_l1_block_alloc(int cluster_id, int core_id, uint32_t size) {
  if (!daml_in_bounds_cc(cluster_id, core_id)) return 0;
  void *ptr;
  daml_lock_cluster(cluster_id);
  ptr = domain_malloc(&g_hbm_l1_allocators[cluster_id][core_id], size);
  daml_fence();
  daml_unlock_cluster(cluster_id);
  soc_daml_upload_free_list(cluster_id, core_id);
  return ptr;
}

static inline void flex_l1_block_free(int cluster_id, int core_id, void *ptr) {
  if (!daml_in_bounds_cc(cluster_id, core_id)) return;
  daml_lock_cluster(cluster_id);
  domain_free(&g_hbm_l1_allocators[cluster_id][core_id], ptr);
  daml_fence();
  daml_unlock_cluster(cluster_id);
  soc_daml_upload_free_list(cluster_id, core_id);
}

/* ---------- getters ---------- */
static inline uint32_t soc_daml_get_core_free_count(int c, int k) { return daml_in_bounds_cc(c,k) ? g_hbm_core_free_count[c][k] : 0u; }
static inline const daml_block_t* soc_daml_get_core_free_list(int c, int k) { return daml_in_bounds_cc(c,k) ? &g_hbm_core_free[c][k][0] : (const daml_block_t*)0; }
static inline uint32_t soc_daml_get_cluster_common_count(int c) { return daml_in_bounds_cluster(c) ? g_hbm_cluster_common_count[c] : 0u; }
static inline const daml_block_t* soc_daml_get_cluster_common(int c) { return daml_in_bounds_cluster(c) ? &g_hbm_cluster_common[c][0] : (const daml_block_t*)0; }
static inline uint32_t soc_daml_get_system_common_count(void) { return g_hbm_system_common_count; }
static inline const daml_block_t* soc_daml_get_system_common(void) { return &g_hbm_system_common[0]; }
