#pragma once
/*
 * soc_daml.h — HBM-visible allocator metadata & helpers
 *
 * Key changes vs earlier versions:
 *  - Each cluster initializes its own L1 allocators (no remote L1 writes).
 *  - Snapshots of free lists are taken by the *same* cluster that owns the L1.
 *  - Snapshots validate pointers against the local heap range.
 *  - No libc calls; tiny zero/fence helpers are used.
 *
 * Requires:
 *  - flex_cluster_arch.h (generated by `make hw`) for ARCH_* macros
 *  - flex_alloc.h        for alloc_t / alloc_block_t / flex_cluster_alloc_init()
 *  - flex_printf.h       for printf()
 */

#include <stdint.h>
#include <stddef.h>
#include "flex_cluster_arch.h"
#include "flex_runtime.h"
#include "flex_alloc.h"
#include "flex_printf.h"

/* --------------------------
 * Dimensions from platform
 * -------------------------- */
#if defined(ARCH_NUM_CLUSTER)
#define NUM_CLUSTERS         (ARCH_NUM_CLUSTER)
#else
#define NUM_CLUSTERS         (ARCH_NUM_CLUSTER_X * ARCH_NUM_CLUSTER_Y)
#endif
#define CORES_PER_CLUSTER    (ARCH_NUM_CORE_PER_CLUSTER)

/* Heap bounds (per cluster, same numeric range in each cluster’s L1) */
#define HEAP_BASE   (ARCH_CLUSTER_HEAP_BASE)
#define HEAP_END    (ARCH_CLUSTER_HEAP_END)

/* Tunables */
#ifndef MAX_FREE_BLOCKS_PER_CORE
#define MAX_FREE_BLOCKS_PER_CORE  128u
#endif
#ifndef MAX_COMMON_BLOCKS
#define MAX_COMMON_BLOCKS         128u
#endif

/* --------------------------
 * Types
 * -------------------------- */
typedef struct {
  void    *addr;   /* address of free block header in L1 */
  uint32_t size;   /* size in bytes */
} daml_block_t;

/* --------------------------
 * HBM-resident global state
 * -------------------------- */
__attribute__((section(".hbm")))
alloc_t g_hbm_l1_allocators[NUM_CLUSTERS][CORES_PER_CLUSTER];

__attribute__((section(".hbm")))
volatile uint32_t g_hbm_core_free_count[NUM_CLUSTERS][CORES_PER_CLUSTER];

__attribute__((section(".hbm")))
daml_block_t g_hbm_core_free[NUM_CLUSTERS][CORES_PER_CLUSTER][MAX_FREE_BLOCKS_PER_CORE];

__attribute__((section(".hbm")))
volatile uint32_t g_hbm_cluster_common_count[NUM_CLUSTERS];

__attribute__((section(".hbm")))
daml_block_t g_hbm_cluster_common[NUM_CLUSTERS][MAX_COMMON_BLOCKS];

__attribute__((section(".hbm")))
volatile uint32_t g_hbm_system_common_count;

__attribute__((section(".hbm")))
daml_block_t g_hbm_system_common[MAX_COMMON_BLOCKS];

/* Simple locks in HBM (if you later need them) */
__attribute__((section(".hbm")))
volatile int g_cluster_lock[NUM_CLUSTERS];

__attribute__((section(".hbm")))
volatile int g_global_lock;

/* Runtime dimensions (allow using a smaller mesh at run-time if needed) */
__attribute__((section(".hbm")))
static volatile uint32_t g_rt_num_clusters = NUM_CLUSTERS;

__attribute__((section(".hbm")))
static volatile uint32_t g_rt_cores_per_cluster = CORES_PER_CLUSTER;

static inline void soc_daml_set_runtime_dims(uint32_t num_clusters,
                                             uint32_t cores_per_cluster)
{
  g_rt_num_clusters      = (num_clusters      <= NUM_CLUSTERS)      ? num_clusters      : NUM_CLUSTERS;
  g_rt_cores_per_cluster = (cores_per_cluster <= CORES_PER_CLUSTER) ? cores_per_cluster : CORES_PER_CLUSTER;
}

/* --------------------------
 * Tiny utils (no libc)
 * -------------------------- */
static inline void daml_zero_u32(volatile uint32_t *p, uint32_t n) {
  for (uint32_t i = 0; i < n; ++i) p[i] = 0u;
}
static inline void daml_zero_bytes(volatile void *ptr, uint32_t n) {
  volatile uint8_t *q = (volatile uint8_t*)ptr;
  for (uint32_t i = 0; i < n; ++i) q[i] = 0u;
}
static inline void daml_fence(void) { __sync_synchronize(); }

/* --------------------------
 * Debug helpers
 * -------------------------- */
#ifndef BOOT_LOG
#define BOOT_LOG(...)   printf(__VA_ARGS__)
#endif
#ifndef SNAP_LOG
#define SNAP_LOG(...)   printf(__VA_ARGS__)
#endif

/* --------------------------
 * Arena math (per-core L1)
 * -------------------------- */
static inline void daml_compute_core_arena(uint32_t *out_base,
                                           uint32_t *out_size,
                                           uint32_t core_id)
{
  const uint32_t heap_base = (uint32_t)HEAP_BASE;
  const uint32_t heap_end  = (uint32_t)HEAP_END;
  const uint32_t heap_size = (heap_end > heap_base) ? (heap_end - heap_base) : 0u;

  uint32_t share = (g_rt_cores_per_cluster > 0) ? heap_size / g_rt_cores_per_cluster : 0u;

  /* Keep block alignment compatible with allocator’s MIN_BLOCK_SIZE (sizeof alloc_block_t) */
  const uint32_t align = (uint32_t)sizeof(alloc_block_t);
  share = (share / align) * align;

  uint32_t base = heap_base + core_id * share;
  uint32_t size = (core_id == (g_rt_cores_per_cluster - 1)) ? (heap_end - base) : share;
  size = (size / align) * align;

  *out_base = base;
  *out_size = size;
}

/* --------------------------
 * Per-cluster allocator init
 * (must be called by *this cluster*)
 * -------------------------- */
static inline void soc_daml_init_allocators_this_cluster(uint32_t cid)
{
  /* Clear metadata for this cluster */
  g_hbm_cluster_common_count[cid] = 0u;
  daml_zero_bytes(&g_hbm_cluster_common[cid][0], (uint32_t)sizeof(g_hbm_cluster_common[cid]));
  for (uint32_t k = 0; k < g_rt_cores_per_cluster; ++k) {
    g_hbm_core_free_count[cid][k] = 0u;
    daml_zero_bytes(&g_hbm_core_free[cid][k][0], (uint32_t)sizeof(g_hbm_core_free[cid][k]));
  }
  daml_fence();

  /* Initialize the L1 allocator for each core of THIS cluster.
     The call writes the first free block header into local L1,
     so it must run on the owning cluster. */
  for (uint32_t kid = 0; kid < g_rt_cores_per_cluster; ++kid) {
    uint32_t base, size;
    daml_compute_core_arena(&base, &size, kid);

    flex_cluster_alloc_init(&g_hbm_l1_allocators[cid][kid], (void*)base, size);

    BOOT_LOG("    [BOOT] C%u/K%u arena: [0x%08x .. 0x%08x) size=0x%08x\n",
             cid, kid, base, base + size, size);
  }
}

/* --------------------------
 * Snapshot free list for (cid,kid)
 * (must be called by that cluster)
 * -------------------------- */
static inline void soc_daml_upload_free_list(uint32_t cid, uint32_t kid)
{
  const uint32_t heap_lo = (uint32_t)HEAP_BASE;
  const uint32_t heap_hi = (uint32_t)HEAP_END;

  SNAP_LOG("[SNAPSHOT] Enter C%u/K%u\n", cid, kid);

  g_hbm_core_free_count[cid][kid] = 0u;
  daml_fence();

  alloc_t       *alloc = &g_hbm_l1_allocators[cid][kid];
  alloc_block_t *curr  = alloc->first_block;
  uint32_t count = 0u;

  while (curr && (count < MAX_FREE_BLOCKS_PER_CORE)) {
    uint32_t p = (uint32_t)curr;

    /* Validate pointer lies inside [heap_lo, heap_hi) for THIS cluster */
    if (p < heap_lo || (p + (uint32_t)sizeof(alloc_block_t)) > heap_hi || (p & (sizeof(alloc_block_t)-1))) {
      SNAP_LOG("[SNAPSHOT][WARN] C%u/K%u bad ptr=0x%08x (lo=0x%08x hi=0x%08x), abort list\n",
               cid, kid, p, heap_lo, heap_hi);
      break;
    }

    g_hbm_core_free[cid][kid][count].addr = (void*)p;
    g_hbm_core_free[cid][kid][count].size = curr->size;

    curr  = curr->next;
    count += 1u;
  }

  daml_fence();
  g_hbm_core_free_count[cid][kid] = count;

  SNAP_LOG("[SNAPSHOT] Uploaded C%u/K%u blocks=%u\n", cid, kid, count);
}

/* --------------------------
 * Build per-cluster common
 * (intersection across cores)
 * -------------------------- */
static inline void soc_daml_build_cluster_common(uint32_t cid)
{
  uint32_t out_cnt = 0u;
  g_hbm_cluster_common_count[cid] = 0u;
  daml_fence();

  if (g_rt_cores_per_cluster == 0u) return;

  const uint32_t ref_n = g_hbm_core_free_count[cid][0];
  for (uint32_t i = 0; i < ref_n && out_cnt < MAX_COMMON_BLOCKS; ++i) {
    const daml_block_t cand = g_hbm_core_free[cid][0][i];
    int in_all = 1;
    for (uint32_t k = 1; k < g_rt_cores_per_cluster; ++k) {
      /* scan list k */
      const uint32_t n = g_hbm_core_free_count[cid][k];
      int found = 0;
      for (uint32_t j = 0; j < n; ++j) {
        if (g_hbm_core_free[cid][k][j].addr == cand.addr &&
            g_hbm_core_free[cid][k][j].size == cand.size) { found = 1; break; }
      }
      if (!found) { in_all = 0; break; }
    }
    if (in_all) {
      g_hbm_cluster_common[cid][out_cnt] = cand;
      out_cnt += 1u;
    }
  }

  daml_fence();
  g_hbm_cluster_common_count[cid] = out_cnt;
}

/* --------------------------
 * Build system common
 * (intersection across clusters)
 * -------------------------- */
static inline void soc_daml_build_system_common(void)
{
  uint32_t out_cnt = 0u;
  g_hbm_system_common_count = 0u;
  daml_fence();

  if (g_rt_num_clusters == 0u) return;

  const uint32_t ref_n = g_hbm_cluster_common_count[0];
  for (uint32_t i = 0; i < ref_n && out_cnt < MAX_COMMON_BLOCKS; ++i) {
    const daml_block_t cand = g_hbm_cluster_common[0][i];
    int in_all = 1;
    for (uint32_t c = 1; c < g_rt_num_clusters; ++c) {
      const uint32_t n = g_hbm_cluster_common_count[c];
      int found = 0;
      for (uint32_t j = 0; j < n; ++j) {
        if (g_hbm_cluster_common[c][j].addr == cand.addr &&
            g_hbm_cluster_common[c][j].size == cand.size) { found = 1; break; }
      }
      if (!found) { in_all = 0; break; }
    }
    if (in_all) {
      g_hbm_system_common[out_cnt] = cand;
      out_cnt += 1u;
    }
  }

  daml_fence();
  g_hbm_system_common_count = out_cnt;
}

/* --------------------------
 * Getters (optional)
 * -------------------------- */
static inline uint32_t soc_daml_get_core_free_count(uint32_t cid, uint32_t kid) {
  return (cid < NUM_CLUSTERS && kid < CORES_PER_CLUSTER) ? g_hbm_core_free_count[cid][kid] : 0u;
}
static inline const daml_block_t* soc_daml_get_core_free(uint32_t cid, uint32_t kid) {
  return (cid < NUM_CLUSTERS && kid < CORES_PER_CLUSTER) ? &g_hbm_core_free[cid][kid][0] : (const daml_block_t*)0;
}
static inline uint32_t soc_daml_get_cluster_common_count(uint32_t cid) {
  return (cid < NUM_CLUSTERS) ? g_hbm_cluster_common_count[cid] : 0u;
}
static inline const daml_block_t* soc_daml_get_cluster_common(uint32_t cid) {
  return (cid < NUM_CLUSTERS) ? &g_hbm_cluster_common[cid][0] : (const daml_block_t*)0;
}
static inline uint32_t soc_daml_get_system_common_count(void) {
  return g_hbm_system_common_count;
}
static inline const daml_block_t* soc_daml_get_system_common(void) {
  return &g_hbm_system_common[0];
}
